LP RPC subscription docs
chainflip-io/chainflip-docs pull request #38
Opened 2023-10-09 08:36 UTC by kylezs

Closes: PRO-872

Adds documentation for the two LP subscriptions we have at the moment.

2023-10-11 10:39 UTC, ben-jit commented on pages/integration/liquidity-provision/how-liquidity-provision-works.mdx
> +1. **Creating a Liquidity Provider Account**: Liquidity providers need an account on the Chainflip State Chain. This account is needed so their assets and orders can be associated to them. The **Stat
... nominal amount of $FLIP to cover gas fees **for** operations ... ?

2023-10-11 10:44 UTC, ben-jit commented on pages/integration/liquidity-provision/how-liquidity-provision-works.mdx
> +2. **Depositing Assets to a Liquidity Account**: Liquidity Providers nominate the assets they wish to deposit. To do so they will also need to specify a refund address, which may be used to send back
... which may be used to send back the LPs deposits ... 

I would tighten this up. It's a bit of a scary statement otherwise. 
Maybe:

"To do so, a refund address must be specified in order to return LP deposits in case of _(insert example reasons, e.g. timeout)_. Additionally, this allows the protocol to correct the security ratio."

2023-10-11 10:48 UTC, ben-jit commented on pages/integration/liquidity-provision/liquidity-provision-basics.mdx
> +In the context of Chainflip, liquidity provisioning is the process of supplying assets to the Chainflip protocol's liquidity pools. By providing liquidity, you're essentially lending your assets to t
Can we change the use of lending? It implies I get back the full amount.

Maybe:
"By providing liquidity, you're essentially submitting your assets to the protocol to be used in the pools for asset swapping."

2023-10-11 10:57 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
> +- The external chain the withdrawal address is for as a camel-case string, eg "Ethereum" or "Polkadot"
Can we tighten a bit?
E.g.
"The external chain for the asset to be withdrawn as a camel-case string, e.g. "Ethereum" or "Polkadot".

Not sure if that's any better? It's a tricky sentence.

2023-10-11 11:00 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
> +- Withdraw address. The format depends on which external chain the address is for, eg ss58 encoding for "Polkadot" withdrawal addresses
Alternative:
"Withdrawal address, the format of which depends on the external chain the asset is associated with, e.g. ..."

2023-10-11 11:03 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
> +- A JSON object specifying how much to change the order. This can be provided in two different ways:
I think an example would be great here. For instance:
e.g. 

1. range order changed by liquidity
2. range order changed by asset amount

Use one sentence to explain the example.

2023-10-11 11:06 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
> +- A JSON object specifying the new size of the order. This can be provided in two different ways:
Some examples again. Maybe do a small section after this with a couple of examples.

LPs are dumb by default.

2023-10-11 11:07 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
> +- (Optional) Price tick as i32. If not specified the previous tick of this order id will be used.
Decide if full stops at end of lists or not. Either way is cool but not a mix

2023-10-11 11:13 UTC, ben-jit commented on pages/integration/liquidity-provision/lp-api.mdx
>  ## Working Example
Can we extend this working example to include all api calls ? Just to have demos of expected inputs and what we should expect out?

2023-10-11 11:13 UTC, ben-jit requested changes
Small changes in comments. 

Awesome job overall though guys !

2023-10-12 10:02 UTC, AlastairHolmes commented on pages/integration/liquidity-provision/how-liquidity-provision-works.mdx
> +2. **Depositing Assets to a Liquidity Account**: Liquidity Providers nominate the assets they wish to deposit. To do so they will also need to specify a refund address, which may be used to send back
The thing is the address I'm referring to is only for the purpose of correcting the security ratio. I can omit the explanation (which is actually "correct" in the sense the security ratio correction is not implemented in code, but I believe is a manual process). So I could just state that you must specify a refund address.

2023-10-12 11:30 UTC, AlastairHolmes commented on pages/integration/liquidity-provision/liquidity-provision-basics.mdx
> +In the context of Chainflip, liquidity provisioning is the process of supplying assets to the Chainflip protocol's liquidity pools. By providing liquidity, you're essentially lending your assets to t
How about: "By providing liquidity, you're essentially stating your willingness to sell assets in return for other assets and some earned fees. Thereby facilitating swaps"

2023-10-23 12:35 UTC, ben-jit approved these changes

2023-10-23 12:42 UTC, AlastairHolmes commented on pages/integration/liquidity-provision/lp-api.mdx
> +- (Optional) A JSON array of two i32, representing the start and end of the price range the order is over. If not specified the previous tick range of this order id will be used. The first number sho
No this is correct.

2023-10-23 12:55 UTC, merged